[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/status"
  to = "/.netlify/functions/checkStatus"
  status = 200

[[redirects]]
  from = "/api/status/*"
  to = "/.netlify/functions/checkStatus/:splat"
  status = 200
